### PR TITLE
Printing XML file input in logger

### PR DESCRIPTION
**Pull request by ChristianVonMach**
Solving #88 by printing the XML file with an logger.

The Output looks like this
```
[2021-01-17 18:39:03.906] [XMLFile] [debug] <?xml version="1.0" encoding="UTF-8" ?>
[2021-01-17 18:39:03.906] [XMLFile] [debug] <ARTSS>
[2021-01-17 18:39:03.906] [XMLFile] [debug]   <physical_parameters>
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <t_end> 2.0 </t_end>  <!-- simulation end time -->
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <dt> 0.001 </dt>  <!-- time stepping, caution: CFL-condition dt < 0.5*dx^2/nu -->
[2021-01-17 18:39:03.906] [XMLFile] [debug]   </physical_parameters>
[2021-01-17 18:39:03.906] [XMLFile] [debug] 
[2021-01-17 18:39:03.906] [XMLFile] [debug]   <solver description="AdvectionSolver" >
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <advection type="SemiLagrangian" field="u,v,w">
[2021-01-17 18:39:03.906] [XMLFile] [debug]     </advection>
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <solution available="Yes">
[2021-01-17 18:39:03.906] [XMLFile] [debug]       <tol> 1e-03 </tol>  <!-- tolerance for further tests -->
[2021-01-17 18:39:03.906] [XMLFile] [debug]     </solution>
[2021-01-17 18:39:03.906] [XMLFile] [debug]   </solver>
[2021-01-17 18:39:03.906] [XMLFile] [debug] 
[2021-01-17 18:39:03.906] [XMLFile] [debug]   <domain_parameters>
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <X1> 0. </X1>  <!-- physical domain -->
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <X2> 2.0 </X2>
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <Y1> 0. </Y1>
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <Y2> 2.0 </Y2>
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <Z1> 0. </Z1>
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <Z2> 1.0 </Z2>
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <x1> 0. </x1>  <!-- computational domain -->
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <x2> 2.0 </x2>
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <y1> 0. </y1>
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <y2> 2.0 </y2>
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <z1> 0. </z1>
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <z2> 1.0 </z2>
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <nx> 40 </nx>  <!-- grid resolution (number of cells excl. ghost cells) -->
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <ny> 40 </ny>
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <nz> 1 </nz>
[2021-01-17 18:39:03.906] [XMLFile] [debug]   </domain_parameters>
[2021-01-17 18:39:03.906] [XMLFile] [debug] 
[2021-01-17 18:39:03.906] [XMLFile] [debug]   <adaption dynamic="No" data_extraction="No"> </adaption>
[2021-01-17 18:39:03.906] [XMLFile] [debug] 
[2021-01-17 18:39:03.906] [XMLFile] [debug]   <boundaries>
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <boundary field="u,v,w" patch="front,back,left,right,bottom,top" type="dirichlet" value="0.0" />
[2021-01-17 18:39:03.906] [XMLFile] [debug]   </boundaries>
[2021-01-17 18:39:03.906] [XMLFile] [debug] 
[2021-01-17 18:39:03.906] [XMLFile] [debug]   <obstacles enabled="No"/>
[2021-01-17 18:39:03.906] [XMLFile] [debug] 
[2021-01-17 18:39:03.906] [XMLFile] [debug]   <surfaces enabled="No"/>
[2021-01-17 18:39:03.906] [XMLFile] [debug] 
[2021-01-17 18:39:03.906] [XMLFile] [debug]   <initial_conditions usr_fct="GaussBubble"  random="No">  <!-- Gaussian function  -->
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <u_lin> 0.5 </u_lin>      <!-- x-velocity in linear case  -->
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <v_lin> 0.5 </v_lin>      <!-- y-velocity in linear case  -->
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <w_lin> 0.25 </w_lin>     <!-- z-velocity in linear case  -->
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <xshift> 1.025 </xshift>  <!-- xshift of Gauss Bubble in domain  -->
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <yshift> 1.025 </yshift>  <!-- yshift of Gauss Bubble in domain  -->
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <zshift> 0.5 </zshift>    <!-- zshift of Gauss Bubble in domain  -->
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <l> 0.03125 </l>          <!-- sigma in Gaussian -->
[2021-01-17 18:39:03.906] [XMLFile] [debug]   </initial_conditions>
[2021-01-17 18:39:03.906] [XMLFile] [debug] 
[2021-01-17 18:39:03.906] [XMLFile] [debug]   <visualisation save_vtk="Yes" save_csv="No">
[2021-01-17 18:39:03.906] [XMLFile] [debug]     <vtk_nth_plot> 200 </vtk_nth_plot>
[2021-01-17 18:39:03.906] [XMLFile] [debug]   </visualisation>
[2021-01-17 18:39:03.906] [XMLFile] [debug] 
[2021-01-17 18:39:03.906] [XMLFile] [debug]   <logging file="output_test_advection.log" level="info">
[2021-01-17 18:39:03.906] [XMLFile] [debug]   </logging>
[2021-01-17 18:39:03.906] [XMLFile] [debug] </ARTSS>
[2021-01-17 18:39:03.906] [XMLFile] [debug] <!-- eResult=0, filename=../tests/advection/Test_Advection.xml -->
[2021-01-17 18:39:03.906] [P6Domain] [debug] ############### Domain Parameter ###############
[2021-01-17 18:39:03.906] [P6Domain] [debug] For Level 0 Nx: 42, Ny: 42, Nz: 3
[2021-01-17 18:39:03.906] [P6Domain] [debug] For Level 0 nx: 42, ny 42, nz 3
...
```
(started with `./bin/artss_serial ../tests/advection/Test_Advection.xml`)

which is easy to grep.

An open question would be what to to with an corrupt XML file. Tinyxml will probably die in the process of parsing and without the specification of `loglevel` and `logfile` no useful output could be written.

### CODE REVIEW

**Review by LinhWuerzburger — CHANGES_REQUESTED** [review]
grepping the XML file and putting it into the log file was not the intention of this issue. rather than the parsed content should be printed. 

for example:
[XML file] [debug] physical_parameters: t_end: 2.0

For me, there is no reason to copy the content of the XML file to the logger. If a problem is occurring because of the wrong format, the XML file should be attached. The meaning of adding the parameters is to see which values the program uses.
There is already some output which can be used for that, for example, the print function of the Field class, which doesn't need to be doubled, but other parameters like physical_parameters are nowhere to be found. The reasoning behind it is to see with which parameters ARTSS is calculating and to be able to recreate the XML file while minimising the duplicate output in the log file.

Summary: You have to be able to recreate your used XML file through the logging file, but not through including the file in their XML format.

**Comment by ChristianVonMach** [comment]
new format for xml printing
```
[2021-01-23 18:59:30.036] [XMLFile] [debug] ARTSS/physical_parameters/t_end =  2.0 
[2021-01-23 18:59:30.036] [XMLFile] [debug] ARTSS/physical_parameters/dt =  0.001 
[2021-01-23 18:59:30.036] [XMLFile] [debug] ARTSS/solver<description = AdvectionSolver>
[2021-01-23 18:59:30.036] [XMLFile] [debug] ARTSS/solver/advection<type = SemiLagrangian>
[2021-01-23 18:59:30.036] [XMLFile] [debug] ARTSS/solver/advection<field = u,v,w>
[2021-01-23 18:59:30.036] [XMLFile] [debug] ARTSS/solver/solution<available = Yes>
[2021-01-23 18:59:30.036] [XMLFile] [debug] ARTSS/solver/solution/tol =  1e-03 
[2021-01-23 18:59:30.036] [XMLFile] [debug] ARTSS/domain_parameters/X1 =  0. 
[2021-01-23 18:59:30.036] [XMLFile] [debug] ARTSS/domain_parameters/X2 =  2.0 
[2021-01-23 18:59:30.036] [XMLFile] [debug] ARTSS/domain_parameters/Y1 =  0. 
```

lines like `/root/child/child->child/<attribute = value>` are attributes of a node all other lines are XML nodes with text.

**Comment by LinhWuerzburger** [comment]
is it possible to add the filename? so far I am happy with the changes and if it is not possible, I would accept the PR. 
My idea is to clearly indicate the beginning and the easiest way would be the file name, do you agree?

**Comment by ChristianVonMach** [comment]
> is it possible to add the filename? so far I am happy with the changes and if it is not possible, I would accept the PR.
> My idea is to clearly indicate the beginning and the easiest way would be the file name, do you agree?

This is easily done. Do you like to have a special format or just the plain filename? For example

```
debug   : Test_Advection.xml
debug   : ARTSS/physical_parameters/t_end =  2.0 
debug   : ARTSS/physical_parameters/dt =  0.001 
debug   : ARTSS/solver<description = AdvectionSolver>
debug   : ARTSS/solver/advection<type = SemiLagrangian>
debug   : ARTSS/solver/advection<field = u,v,w>
debug   : ARTSS/solver/solution<available = Yes>
debug   : ARTSS/solver/solution/tol =  1e-03 
debug   : ARTSS/domain_parameters/X1 =  0. 
debug   : ARTSS/domain_parameters/X2 =  2.0 
debug   : ARTSS/domain_parameters/Y1 =  0. 
debug   : ARTSS/domain_parameters/Y2 =  2.0 
debug   : ARTSS/domain_parameters/Z1 =  0. 
debug   : ARTSS/domain_parameters/Z2 =  1.0 
debug   : ARTSS/domain_parameters/x1 =  0. 
debug   : ARTSS/domain_parameters/x2 =  2.0 
debug   : ARTSS/domain_parameters/y1 =  0. 
debug   : ARTSS/domain_parameters/y2 =  2.0 
debug   : ARTSS/domain_parameters/z1 =  0. 
debug   : ARTSS/domain_parameters/z2 =  1.0 
```

**Comment by LinhWuerzburger** [comment]
something to mark the beginning, so that if there are several simulations in one log file, you can jump there. this could be for example: start the simulation of [XML filename]. the exact wording is not important. if possible something unique, to make it easier to search for. this can be of course just a long sentence.

**Review by LinhWuerzburger — APPROVED** [review]

**Pull request merged**
