### PR TITLE
Update PGI docker container

### LINKED ISSUE #96: Update PGI docker container
Nvidia discontinued the PGI docker container due to rebranding PGI to NVHPC compiler.

Basically the name of the container changed to _https://ngc.nvidia.com/catalog/containers/nvidia:nvhpc_

see: https://forums.developer.nvidia.com/t/ngc-pgi-docker-container-unusable/158542

all docker pull commands need to be replaced with the new name

### PR DESCRIPTION
**Pull request by ChristianVonMach**
attempt to close #96

### CODE REVIEW

**Review by LinhWuerzburger — CHANGES_REQUESTED** [review]
image

image

compiled in docker with ./compile.sh -d --cc 60 -s -m -g --gb

serial and multicore version compiled successfully

**Review by LinhWuerzburger — CHANGES_REQUESTED** [review]
image
This error occurs for the ns temp buoyancy test as well the turbulent version (ns temp turb buoyancy).

I guess, there is only a copyin command missing, but I didn't check it out yet.

**Comment by LinhWuerzburger** [comment]
but I am glad to see that the release version now also works/compiles fine

**Comment by LinhWuerzburger** [comment]
pcopy may fix the problem with the missing field in the GPU memory, but the important question is: why is it missing on the GPU? there may be a conceptual error. every necessary field should be copied to the GPU in FieldController.cpp (constructor) and nowhere else. Therefore I highly recommend staying with the present clause and to look for the cause for that. Thou, I don't know, why it worked so far.

**Review by LinhWuerzburger — CHANGES_REQUESTED** [review]
as mentioned before that is not a valid solution in terms of software structure.
found the error in SolverController.cpp:511. calling the copy constructor overwrites the pointer of the data field which was already copied to the GPU memory. This results in a new for the GPU unknown data field and leads to the error. I suggest a new function for the Field Class where only the content of the data field is copied.

**Comment by LinhWuerzburger** [comment]
and as mentioned in the issue compute compatibility minimum is cc35, therefore the description of the compile script has to be changed as well

**Comment by ChristianVonMach** [comment]
> as mentioned before that is not a valid solution in terms of software structure.
> found the error in SolverController.cpp:511. calling the copy constructor overwrites the pointer of the data field which was already copied to the GPU memory. This results in a new for the GPU unknown data field and leads to the error. I suggest a new function for the Field Class where only the content of the data field is copied.

done in f832449eb7819893e94b46e7cb1d2f67691ba55c
followed the suggested way of adding a function copy_data in class Field.

**Review by LinhWuerzburger — APPROVED** [review]

**Pull request merged**
